version: '3'
services:
  mysqldb:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=Rahul@1234
      - MYSQL_DATABASE=myinvoices
    volumes:
      - mysql-data1:/var/lib/mysql

volumes:
  mysql-data1:
    driver: local