---
- hosts: "{{ server1 }}"
  tasks:
  - name: First Server
    become: yes
    script: /etc/ansible/roles/script/backupAll.py {{ All }} {{ Conf }} {{ Configuration }} {{ Lib }} {{ Properties }} {{ Ear }} {{ Static }} {{ DynamicJars }} {{ server1 }} {{ env }} {{ dc }} {{ backupFolder }} {{ prvfle }}
    register: FirstServerStatus
    args:
     executable: python3
  - name: FirstServerOutPut
    debug:
     msg: "{{ FirstServerStatus.stdout_lines }}"
    when: "{{ FirstServerStatus.stdout is defined }}"

- hosts: "{{ AnsibleServer }}"
  tasks:
  - name: EmailNotification for One Server
    become: yes     
    script: /etc/ansible/roles/script/emailNotification.py {{ receivers }} {{ smtpserver }} "{{ hostvars[server1].FirstServerStatus.stdout }}" 
    register: EmailOutput
    args:
     executable: python3
    when: "{{ hostvars[server1].FirstServerStatus.stdout is defined }}"
    notify:
    - OutputOfEmailNotification
  handlers:
  - name: OutputOfEmailNotification
    debug:
     msg: " {{ EmailOutput.stdout_lines }} "