---
- hosts: "{{ server1 }}"
  tasks:
  - name: First Server
    become: yes
    script: /etc/ansible/roles/script/deploymentApache.py {{ Restart }} {{ Static }} {{ server1 }} {{ app }} {{ env }} {{ serviceName }} {{ dc }} {{ staticFolder }} {{ rtdFolder }} {{ rtdPath }} {{ earName }} "false" {{ prvfle }}
    register: FirstServerStatus
    args:
     executable: python3
  - name: FirstServerOutPut
    debug:
     msg: "{{ FirstServerStatus.stdout_lines }}"
    when: "{{ FirstServerStatus.stdout is defined }}"
  - name: count
    debug:
     msg: "{{ FirstServerStatus.stdout.find('Go for next instance') }}"
    when: "{{ FirstServerStatus.stdout is defined }}"

- hosts: "{{ AnsibleServer }}"
  tasks:
  - name: EmailNotification for One Server
    become: yes
    script: /etc/ansible/roles/script/emailNotification.py {{ receivers }} {{ smtpserver }} "{{ hostvars[server1].FirstServerStatus.stdout }}"
    register: EmailOutput
    args:
     executable: python3
    when: "{{ hostvars[server1].FirstServerStatus.stdout is defined }}"
    notify:
    - OutputOfEmailNotification
  handlers:
  - name: OutputOfEmailNotification
    debug:
     msg: " {{ EmailOutput.stdout_lines }} "

- hosts: "{{ AnsibleServer }}"
  tasks:
  - name: Build Status
    become: yes
    script: /etc/ansible/roles/script/buildStatusFY.py
    args:
     executable: python3
    when: "{{ hostvars[server1].FirstServerStatus.stdout.find('Go for next instance') == -1 }}"