---
- hosts: localhost
  gather_facts: no
  connection: local
  vars:
    - first_nm: John
    - last_nm: Smith
    - nick_nm: test
  tasks:
   - set_fact: full_name="{{first_nm}} {{last_nm}}{% if nick_nm is defined and nick_nm %}{{nick_nm}}{%endif%}"
   - debug: var=full_name