---
- hosts: nsweb05
  tasks:
  - name: Copy and Execute the AUS script
    become: yes
    script: /etc/ansible/roles/script/usfile.sh

  - name: Copy and Execute the EU script
    become: yes
    script: /etc/ansible/roles/script/eufile.sh

  - name: Copy and Execute the UK script
    become: yes
    script: /etc/ansible/roles/script/ukfile.sh